//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace Sorting.cn.com.sngoo.app7 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://scyueve.f3322.net/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyPassWordOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyUserRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadGoodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteIntoFJOperationCompleted;
        
        private System.Threading.SendOrPostCallback readFJINFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ALterWeightOperationCompleted;
        
        private System.Threading.SendOrPostCallback searcheGoodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGoodsClassOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::Sorting.Properties.Settings.Default.Sorting_cn_com_sngoo_app7_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event verifyPassWordCompletedEventHandler verifyPassWordCompleted;
        
        /// <remarks/>
        public event verifyUserRoleCompletedEventHandler verifyUserRoleCompleted;
        
        /// <remarks/>
        public event searchContentCompletedEventHandler searchContentCompleted;
        
        /// <remarks/>
        public event ReadGoodsCompletedEventHandler ReadGoodsCompleted;
        
        /// <remarks/>
        public event WriteIntoFJCompletedEventHandler WriteIntoFJCompleted;
        
        /// <remarks/>
        public event readFJINFOCompletedEventHandler readFJINFOCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event ALterWeightCompletedEventHandler ALterWeightCompleted;
        
        /// <remarks/>
        public event searcheGoodsCompletedEventHandler searcheGoodsCompleted;
        
        /// <remarks/>
        public event GetGoodsClassCompletedEventHandler GetGoodsClassCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/HelloWorld", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/verifyPassWord", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verifyPassWord(string id, string ps) {
            object[] results = this.Invoke("verifyPassWord", new object[] {
                        id,
                        ps});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verifyPassWordAsync(string id, string ps) {
            this.verifyPassWordAsync(id, ps, null);
        }
        
        /// <remarks/>
        public void verifyPassWordAsync(string id, string ps, object userState) {
            if ((this.verifyPassWordOperationCompleted == null)) {
                this.verifyPassWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyPassWordOperationCompleted);
            }
            this.InvokeAsync("verifyPassWord", new object[] {
                        id,
                        ps}, this.verifyPassWordOperationCompleted, userState);
        }
        
        private void OnverifyPassWordOperationCompleted(object arg) {
            if ((this.verifyPassWordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyPassWordCompleted(this, new verifyPassWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/verifyUserRole", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verifyUserRole(string id) {
            object[] results = this.Invoke("verifyUserRole", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verifyUserRoleAsync(string id) {
            this.verifyUserRoleAsync(id, null);
        }
        
        /// <remarks/>
        public void verifyUserRoleAsync(string id, object userState) {
            if ((this.verifyUserRoleOperationCompleted == null)) {
                this.verifyUserRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyUserRoleOperationCompleted);
            }
            this.InvokeAsync("verifyUserRole", new object[] {
                        id}, this.verifyUserRoleOperationCompleted, userState);
        }
        
        private void OnverifyUserRoleOperationCompleted(object arg) {
            if ((this.verifyUserRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyUserRoleCompleted(this, new verifyUserRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/searchContent", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string searchContent(string classname, string indexclass, string indexcontent, string tablename) {
            object[] results = this.Invoke("searchContent", new object[] {
                        classname,
                        indexclass,
                        indexcontent,
                        tablename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void searchContentAsync(string classname, string indexclass, string indexcontent, string tablename) {
            this.searchContentAsync(classname, indexclass, indexcontent, tablename, null);
        }
        
        /// <remarks/>
        public void searchContentAsync(string classname, string indexclass, string indexcontent, string tablename, object userState) {
            if ((this.searchContentOperationCompleted == null)) {
                this.searchContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchContentOperationCompleted);
            }
            this.InvokeAsync("searchContent", new object[] {
                        classname,
                        indexclass,
                        indexcontent,
                        tablename}, this.searchContentOperationCompleted, userState);
        }
        
        private void OnsearchContentOperationCompleted(object arg) {
            if ((this.searchContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchContentCompleted(this, new searchContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/ReadGoods", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Goods[] ReadGoods(string fruitClass) {
            object[] results = this.Invoke("ReadGoods", new object[] {
                        fruitClass});
            return ((Goods[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadGoodsAsync(string fruitClass) {
            this.ReadGoodsAsync(fruitClass, null);
        }
        
        /// <remarks/>
        public void ReadGoodsAsync(string fruitClass, object userState) {
            if ((this.ReadGoodsOperationCompleted == null)) {
                this.ReadGoodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadGoodsOperationCompleted);
            }
            this.InvokeAsync("ReadGoods", new object[] {
                        fruitClass}, this.ReadGoodsOperationCompleted, userState);
        }
        
        private void OnReadGoodsOperationCompleted(object arg) {
            if ((this.ReadGoodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadGoodsCompleted(this, new ReadGoodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/WriteIntoFJ", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WriteIntoFJ(GoodsView info) {
            this.Invoke("WriteIntoFJ", new object[] {
                        info});
        }
        
        /// <remarks/>
        public void WriteIntoFJAsync(GoodsView info) {
            this.WriteIntoFJAsync(info, null);
        }
        
        /// <remarks/>
        public void WriteIntoFJAsync(GoodsView info, object userState) {
            if ((this.WriteIntoFJOperationCompleted == null)) {
                this.WriteIntoFJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteIntoFJOperationCompleted);
            }
            this.InvokeAsync("WriteIntoFJ", new object[] {
                        info}, this.WriteIntoFJOperationCompleted, userState);
        }
        
        private void OnWriteIntoFJOperationCompleted(object arg) {
            if ((this.WriteIntoFJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteIntoFJCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/readFJINFO", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GoodsView[] readFJINFO(string StarTime, string EndTime, string Username) {
            object[] results = this.Invoke("readFJINFO", new object[] {
                        StarTime,
                        EndTime,
                        Username});
            return ((GoodsView[])(results[0]));
        }
        
        /// <remarks/>
        public void readFJINFOAsync(string StarTime, string EndTime, string Username) {
            this.readFJINFOAsync(StarTime, EndTime, Username, null);
        }
        
        /// <remarks/>
        public void readFJINFOAsync(string StarTime, string EndTime, string Username, object userState) {
            if ((this.readFJINFOOperationCompleted == null)) {
                this.readFJINFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreadFJINFOOperationCompleted);
            }
            this.InvokeAsync("readFJINFO", new object[] {
                        StarTime,
                        EndTime,
                        Username}, this.readFJINFOOperationCompleted, userState);
        }
        
        private void OnreadFJINFOOperationCompleted(object arg) {
            if ((this.readFJINFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.readFJINFOCompleted(this, new readFJINFOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/Delete", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Delete(string FJ_id) {
            this.Invoke("Delete", new object[] {
                        FJ_id});
        }
        
        /// <remarks/>
        public void DeleteAsync(string FJ_id) {
            this.DeleteAsync(FJ_id, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string FJ_id, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        FJ_id}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/ALterWeight", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ALterWeight(string FJ_id, double weight, double TotalPrice, double PuzzleTotlePrice) {
            this.Invoke("ALterWeight", new object[] {
                        FJ_id,
                        weight,
                        TotalPrice,
                        PuzzleTotlePrice});
        }
        
        /// <remarks/>
        public void ALterWeightAsync(string FJ_id, double weight, double TotalPrice, double PuzzleTotlePrice) {
            this.ALterWeightAsync(FJ_id, weight, TotalPrice, PuzzleTotlePrice, null);
        }
        
        /// <remarks/>
        public void ALterWeightAsync(string FJ_id, double weight, double TotalPrice, double PuzzleTotlePrice, object userState) {
            if ((this.ALterWeightOperationCompleted == null)) {
                this.ALterWeightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnALterWeightOperationCompleted);
            }
            this.InvokeAsync("ALterWeight", new object[] {
                        FJ_id,
                        weight,
                        TotalPrice,
                        PuzzleTotlePrice}, this.ALterWeightOperationCompleted, userState);
        }
        
        private void OnALterWeightOperationCompleted(object arg) {
            if ((this.ALterWeightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ALterWeightCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/searcheGoods", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GoodsView searcheGoods(string FJ_id, string UserName) {
            object[] results = this.Invoke("searcheGoods", new object[] {
                        FJ_id,
                        UserName});
            return ((GoodsView)(results[0]));
        }
        
        /// <remarks/>
        public void searcheGoodsAsync(string FJ_id, string UserName) {
            this.searcheGoodsAsync(FJ_id, UserName, null);
        }
        
        /// <remarks/>
        public void searcheGoodsAsync(string FJ_id, string UserName, object userState) {
            if ((this.searcheGoodsOperationCompleted == null)) {
                this.searcheGoodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearcheGoodsOperationCompleted);
            }
            this.InvokeAsync("searcheGoods", new object[] {
                        FJ_id,
                        UserName}, this.searcheGoodsOperationCompleted, userState);
        }
        
        private void OnsearcheGoodsOperationCompleted(object arg) {
            if ((this.searcheGoodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searcheGoodsCompleted(this, new searcheGoodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scyueve.f3322.net/GetGoodsClass", RequestNamespace="http://scyueve.f3322.net/", ResponseNamespace="http://scyueve.f3322.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetGoodsClass() {
            object[] results = this.Invoke("GetGoodsClass", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGoodsClassAsync() {
            this.GetGoodsClassAsync(null);
        }
        
        /// <remarks/>
        public void GetGoodsClassAsync(object userState) {
            if ((this.GetGoodsClassOperationCompleted == null)) {
                this.GetGoodsClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGoodsClassOperationCompleted);
            }
            this.InvokeAsync("GetGoodsClass", new object[0], this.GetGoodsClassOperationCompleted, userState);
        }
        
        private void OnGetGoodsClassOperationCompleted(object arg) {
            if ((this.GetGoodsClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGoodsClassCompleted(this, new GetGoodsClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scyueve.f3322.net/")]
    public partial class Goods {
        
        private string drugCodeField;
        
        private string drugNameField;
        
        private decimal drugPriceField;
        
        private string untisField;
        
        private decimal puzzlePriceField;
        
        /// <remarks/>
        public string DrugCode {
            get {
                return this.drugCodeField;
            }
            set {
                this.drugCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DrugName {
            get {
                return this.drugNameField;
            }
            set {
                this.drugNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal DrugPrice {
            get {
                return this.drugPriceField;
            }
            set {
                this.drugPriceField = value;
            }
        }
        
        /// <remarks/>
        public string Untis {
            get {
                return this.untisField;
            }
            set {
                this.untisField = value;
            }
        }
        
        /// <remarks/>
        public decimal PuzzlePrice {
            get {
                return this.puzzlePriceField;
            }
            set {
                this.puzzlePriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scyueve.f3322.net/")]
    public partial class GoodsView {
        
        private string userTelField;
        
        private string userNameField;
        
        private string drugCodeField;
        
        private string drugNameField;
        
        private decimal drugWeightField;
        
        private string fJ_idField;
        
        private System.DateTime fJ_timeField;
        
        private int packedField;
        
        private decimal drugPriceField;
        
        private decimal totalPriceField;
        
        private decimal puzzlePriceField;
        
        private decimal puzzleTotlePriceField;
        
        private string unitsField;
        
        /// <remarks/>
        public string UserTel {
            get {
                return this.userTelField;
            }
            set {
                this.userTelField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string DrugCode {
            get {
                return this.drugCodeField;
            }
            set {
                this.drugCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DrugName {
            get {
                return this.drugNameField;
            }
            set {
                this.drugNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal DrugWeight {
            get {
                return this.drugWeightField;
            }
            set {
                this.drugWeightField = value;
            }
        }
        
        /// <remarks/>
        public string FJ_id {
            get {
                return this.fJ_idField;
            }
            set {
                this.fJ_idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FJ_time {
            get {
                return this.fJ_timeField;
            }
            set {
                this.fJ_timeField = value;
            }
        }
        
        /// <remarks/>
        public int packed {
            get {
                return this.packedField;
            }
            set {
                this.packedField = value;
            }
        }
        
        /// <remarks/>
        public decimal DrugPrice {
            get {
                return this.drugPriceField;
            }
            set {
                this.drugPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal PuzzlePrice {
            get {
                return this.puzzlePriceField;
            }
            set {
                this.puzzlePriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal PuzzleTotlePrice {
            get {
                return this.puzzleTotlePriceField;
            }
            set {
                this.puzzleTotlePriceField = value;
            }
        }
        
        /// <remarks/>
        public string Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void verifyPassWordCompletedEventHandler(object sender, verifyPassWordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyPassWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyPassWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void verifyUserRoleCompletedEventHandler(object sender, verifyUserRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyUserRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyUserRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void searchContentCompletedEventHandler(object sender, searchContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadGoodsCompletedEventHandler(object sender, ReadGoodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadGoodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadGoodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Goods[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Goods[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WriteIntoFJCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void readFJINFOCompletedEventHandler(object sender, readFJINFOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class readFJINFOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal readFJINFOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GoodsView[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GoodsView[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ALterWeightCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void searcheGoodsCompletedEventHandler(object sender, searcheGoodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searcheGoodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searcheGoodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GoodsView Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GoodsView)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGoodsClassCompletedEventHandler(object sender, GetGoodsClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGoodsClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGoodsClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591